version: "2"
services:
  cnn-config-admin:
    image: registry.services.dmtio.net/cnn-config-admin:0.1.0
    ports:
    - 80:5001
    environment:
      HEALTHCHECK: /hc
      NODE_ENV: development
      PORT: "5001"
